language: ruby
rvm:
  - jruby
  - ruby-head
  - 2.4.1
  - 2.3
  - 2.2
  - 2.1
  - 2.0.0
  - rbx
before_install:
  - 'gem update bundler'
script:
  - NOEXEC_DISABLE=1 rake
notifications:
  irc:
    channels:
      - "irc.freenode.org#rvm-test"
  email:
    recipients:
      - mpapis@gmail.com
    on_failure: change
matrix:
  fast_finish: true
  allow_failures:
    - rvm: rbx
